[project]
name = "rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  # "sentence-transformers>=4.1.0",
  "beautifulsoup4>=4.13.4",
  "google-genai>=1.17.0",
  "pinecone>=7.0.2",
  "requests>=2.32.3",
]
